wordpress-a:
  image: wordpress
  links:
    - db-a:mysql
  ports:
    - 81:80
  labels:
    io.rancher.project.name: JUP
    io.rancher.container.hostname_override: container_name
    io.rancher.container.name: JUPA
  hostname: JUPA

wordpress-b:
  image: wordpress
  links:
    - db-b:mysql
  ports:
    - 82:80
  labels:
    io.rancher.project.name: JUP
    io.rancher.container.hostname_override: container_name
    io.rancher.container.name: JUPB
  hostname: JUPB

db-a:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
  labels:
    io.rancher.project.name: JUPDB
    io.rancher.container.hostname_override: container_name
    io.rancher.container.name: JUPDBA

db-b:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
  labels:
    io.rancher.project.name: JUPDB
    io.rancher.container.hostname_override: container_name
    io.rancher.container.name: JUPDBB