fe:
  image: httpd:2.4
  ports:
    - 81:80
  hostname: fe
  restart: always
  volumes-from: 
    - data
  labels:
    io.rancher.sidekicks: data

fe-data:
  image: httpd:2.4
  volumes:
    - /usr/local/apache2/htdocs/
  labels:
    io.rancher.container.start_once: true
  entrypoint: /bin/true

md:
  image: httpd:2.4
  ports:
    - 82:80
  hostname: md
  restart: always
  volumes-from: 
    - data
  labels:
    io.rancher.sidekicks: data

md-data:
  image: httpd:2.4
  volumes:
    - /usr/local/apache2/htdocs/
  labels:
    io.rancher.container.start_once: true
  entrypoint: /bin/true

msg:
  image: httpd:2.4
  ports:
    - 83:80
  hostname: msg
  restart: always
  volumes-from: 
    - data
  labels:
    io.rancher.sidekicks: data

data:
  image: httpd:2.4
  volumes:
    - /usr/local/apache2/htdocs/
  labels:
    io.rancher.container.start_once: true
  entrypoint: /bin/true
